// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmnpyphrjgvadmezmsue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbnB5cGhyamd2YWRtZXptc3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTgyNzgsImV4cCI6MjA2ODYzNDI3OH0.Ss_pL8onp5qOYV6JvvaWqe6NkPEcihTZVQSB0vcb4CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});